### ISSUE TITLE
Memory Error (and a few updates to original code)

### ISSUE THREAD

**Issue by windowshopr** [PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading#1]
Hey!

Love the work so far. I've noticed a couple of changes to make though. In the first Jupyter Notebook in Chapter 2 ("01_build_itch_order_book.ipynb"), Seaborn was not imported so I ran into an error in the "Buy-Sell Order Distribution" section, so add:

`import seaborn as sns`

...to the top. Also, I was having an issue in the Download/Unzip section at the beginning. Even though I had already downloaded and unzipped the sample file, when I went to run the book again, it was starting to unzip the .gz file all over again, so I also changed the line:

`unzipped = data_path / (filename.stem + '.bin')\n",`

...to:

`unzipped = data_path / (os.path.splitext(SOURCE_FILE)[0] + '.bin')`

...and also need to add:

`import os`

...to the top. This will then properly see that there's already an unzipped file there and won't start to unzip the .gz file again.

Now, I'm running into a memory error and I'm wondering if an external hard drive is actually the solution, or if Windows is just running out of memory from trying to work with such a huge file? My traceback leading up to the memory error looks like this:

Empty DataFrame
Columns: [Message Type, # Trades]
Index: []
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2010099 entries, 0 to 2010098
Data columns (total 9 columns):
timestamp             2010099 non-null datetime64[ns]
buy_sell_indicator    1873082 non-null float64
shares                1995581 non-null float64
price                 1995581 non-null float64
type                  2010099 non-null object
executed_shares       54956 non-null float64
execution_price       500 non-null float64
shares_replaced       14159 non-null float64
price_replaced        14159 non-null float64
dtypes: datetime64[ns](1), float64(7), object(1)
memory usage: 138.0+ MB
<class 'pandas.io.pytables.HDFStore'>
File path: data\order_book.h5
/AAPL/buy                 frame_table  (typ->appendable,nrows->177108242,ncols->2,indexers->[index],dc->[])
/AAPL/messages            frame        (shape->[2010099,9])
/AAPL/sell                frame_table  (typ->appendable,nrows->183264614,ncols->2,indexers->[index],dc->[])
/AAPL/trades              frame        (shape->[59796,3])
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 59796 entries, 2019-03-27 04:00:56.459428646 to 2019-03-27 19:54:05.600648466
Data columns (total 3 columns):
shares    59796 non-null int32
price     59796 non-null int32
cross     59796 non-null int32
dtypes: int32(3)
memory usage: 1.1 MB
None
100,000         0:01:02.811120
200,000         0:01:27.826051
300,000         0:01:28.564991
400,000         0:01:27.096437
500,000         0:01:29.712940
600,000         0:01:29.556783
700,000         0:01:31.360356
800,000         0:01:35.391212
900,000         0:01:35.037438
1,000,000               0:01:56.868902
1,100,000               0:02:12.290003
1,200,000               0:01:42.614183
1,300,000               0:01:51.042871
1,400,000               0:01:41.064018
1,500,000               0:01:48.513128
1,600,000               0:01:41.310528
1,700,000               0:01:52.142803
1,800,000               0:01:44.541379
1,900,000               0:01:48.800505
2,000,000               0:01:48.460462
A    924117
D    869968
X      2789
E     52299
P      6995
F      2282
U     14159
C       473
dtype: int64
<class 'pandas.io.pytables.HDFStore'>
File path: data\order_book.h5
/AAPL/buy                 frame_table  (typ->appendable,nrows->265662363,ncols->2,indexers->[index],dc->[])
/AAPL/messages            frame        (shape->[2010099,9])
/AAPL/sell                frame_table  (typ->appendable,nrows->274896921,ncols->2,indexers->[index],dc->[])
/AAPL/trades              frame        (shape->[59796,3])
Traceback (most recent call last):
  File "01_build_itch_order_book.py", line 464, in <module>
    sell = store['{}/sell'.format(stock)].reset_index().drop_duplicates()
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 4630, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 4687, in duplicated
    labels, shape = map(list, zip(*map(f, vals)))
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 4668, in f
    vals, size_hint=min(len(self), _SIZE_HINT_LIMIT))
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\util\_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\algorithms.py", line 613, in factorize
    na_value=na_value)
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\algorithms.py", line 460, in _factorize_array
    na_value=na_value)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1209, in pandas._libs.hashtable.Int64HashTable.factorize
  File "pandas\_libs\hashtable_class_helper.pxi", line 1104, in pandas._libs.hashtable.Int64HashTable._unique
MemoryError

So I'm assuming it's because every time I try to run the program, it has to chew up a lot of working memory, so is there a way to work around this/work with a smaller ITCH sample/is there anything else you'd recommend? I'd love to be able to continue on working with this. My laptop has plenty of Hard Drive space, RAM is 8GB though.

Thanks for your input!

**Comment by windowshopr** [comment]
Cancel this, I worked with the actual jupyter notebook and it works.
